version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    command: start-dev
    ports:
    - "8085:8080"

    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  keycloak_data:
